### ISSUE TITLE
Object initialisation fails for regular expressions

### ISSUE THREAD

**Issue by perry-mitchell** [anywhichway/switchcase#3]
Great library! I'm already using it extensively. I've noticed one potential bug though - the following doesn't work for the regular expression:

```javascript
const fetchType = switchcase({
    [/webdav|owncloud|nextcloud/]: "webdav",
    dropbox: "dropbox",
    localfile: "localfile"
})(selectedArchiveType);
```

Whenever `selectedArchiveType` is "webdav", "owncloud" or "nextcloud", `fetchType` is undefined. The other values like "dropbox" work fine.

If I modify this to be the following, it works:

```javascript
const fetchTypeSwitch = switchcase()
    .case(/webdav|owncloud|nextcloud/, "webdav")
    .case("dropbox", "dropbox")
    .case("localfile", "localfile");
const fetchType = fetchTypeSwitch(selectedArchiveType);
```

There seems to be something wrong with how the regular expression is used. I'm running this in the latest Chrome.

**Comment by anywhichway** [comment]
@perry-mitchell I just ran the below through the latest Chrome, Firefox, and Edge browsers. I can't reproduce your issue:

```
<html>
<head>
<script src="../index.js"></script>
</head>
<body>
<script>
const fetchType = switchcase({
  [/webdav|owncloud|nextcloud/]: "webdav",
  dropbox: "dropbox",
  localfile: "localfile"
})("webdav");
console.log(fetchType);

const fetchTypeSwitch = switchcase()
    .case(/webdav|owncloud|nextcloud/, "webdav")
    .case("dropbox", "dropbox")
    .case("localfile", "localfile");
console.log(fetchTypeSwitch("webdav"));
</script>
</body>
</html>
```

**Comment by perry-mitchell** [comment]
You're right @anywhichway - Seems on runkit I can't reproduce it anymore. I'll report back if I see it again.

**Comment by anywhichway** [comment]
@perry-mitchell Your closing of this issue six days ago had me revisit the project. I added some new capability based on work related to ReasonDB. You can now use object destructuring and functional pattern matching in switch cases. If you have a few minutes, let me know what you think:

```
const sw = switchcase();
sw.case({address: {city: "Seattle"}},({name}) => name);
sw({name:"joe",address:{city: "Seattle"}},{call:true})); // returns "joe"
```

or

```
const sw = switchcase({},{call:true,functionalMatch:true});
sw.case({address: {city: value => value==="Seattle" || value==="Portland"}},({name}) => name);
sw({name:"joe",address:{city: "Seattle"}}); // returns "joe"
```

and finally full destructuring

```
const sw = switchcase({
	[({address: {city}}) => city==="Seattle" || city==="Portland"]: ({name}) => name;
},{call:true});
sw({name:"joe",address:{city: "Seattle"}})// returns "joe"
```
```

**Comment by perry-mitchell** [comment]
@anywhichway That looks incredibly powerful! Definitely something I'll tap into I'm sure. Your library will be a staple for a lot of my projects. Cheers!

**Comment by anywhichway** [comment]
@perry-mitchell Thanks for the quick response. More coming next week. Below is a unit test that makes the point. Still just 225 lines of code and excluding browserify bloat, less that 3K minified raw file.

```
it("route",function() {
		let logged,
			sw = switchcase({},{pathRouter:true})
				.case("/:id/:name",{req,res} => {
					console.log(logged = {req,res});
				});
		sw({req:{url:"https://www.somesite.com/1/joe"},res:{}});
		expect(logged!==undefined).equal(true);
	})
```
