### ISSUE TITLE
deepFreeze is not defined

### ISSUE THREAD

**Issue by perry-mitchell** [anywhichway/switchcase#4]
Hi,

I've included your library in a webpack project, and am getting the following error:

![image](https://user-images.githubusercontent.com/3869469/52694035-2203e000-2f71-11e9-9776-cebb719d63e5.png)

I thought that perhaps it was how it's being bundled, but then I tried from [Runkit on npm](https://npm.runkit.com/switchcase):

![image](https://user-images.githubusercontent.com/3869469/52694143-6e4f2000-2f71-11e9-95b9-7883a3e387a6.png)

Here's the code I used to reproduce:

```javascript
var switchcase = require("switchcase")

const getResultType = switchcase({
            [/^job\/result\/success/]: "success",
            [/^job\/result\/fail/]: "fail",
            [/^job\/result\/running/]: "running",
            [/^job\/result\/pending/]: "pending",
            default: null
        });
        
getResultType("job/result/fail")
```

**Comment by perry-mitchell** [comment]
In fact, even the example in the readme breaks:

```javascript
let sw = switchcase({
	1: "Case one, a literal",
	[(value) => value===2]: "Case two, a function",
	[/3/]: "Case three, a regular expression",
	[4]: () => "Case four, just demonstrating a functional value",
	default: "Defaulted"
});

console.log(sw(1));
console.log(sw(2));
console.log(sw(3));
console.log(sw(4)()); // note the function invocation
console.log(sw(5));
```

![image](https://user-images.githubusercontent.com/3869469/52694569-cdf9fb00-2f72-11e9-9353-a4acb9cfed7f.png)

So it seems to be an issue with regular expressions..

**Comment by perry-mitchell** [comment]
I feel like if `deepFreeze` was added here: https://github.com/anywhichway/switchcase/blob/146cf8cca353a18a6c4d359ea3bd8d5f9c3b0b98/index.js#L150 - It'd probably work. It's just not in scope. Is there any particular reason that you're eval'ing this code? Perhaps you might consider a PR to handle this in another manner?

**Comment by anywhichway** [comment]
Sorry. I know what broke. We needed an async version of the code and did not want to duplicate all the logic. Did not pass deepFreeze into the scope. The deep freeze is so nobody steps on themselves by modifying a case condition that is an object. Will have a fix in later today and will extend unit tests.

Also, realized there is a way to reduce the code size by 50 percent. Will work that over the next couple of weeks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by anywhichway** [comment]
@perry-mitchell Fixed. Plan to re-engineer code in the next two weeks, so hold on PRs. After that, any PRs you wish to submit are more than welcome!

**Comment by perry-mitchell** [comment]
@anywhichway Thanks! This library rocks. I appreciate the swift fix.

**Comment by anywhichway** [comment]
Thanks Perry. You are welcome.
